SELECT*FROM  REVIEW_NOTICE_VIEW;


CREATE VIEW NOTICES_VIEW
CREATE VIEW NoticesView
AS
SELECT N.*, COUNT(C.CODE) AS CmtCnt 
FROM 
	NOTICES N LEFT OUTER JOIN COMMENTS C ON N.CODE = C.NOTICECODE
GROUP BY N.Code, N.Title, N.Writer, N.Content, N.RegDate, N.Hit; 
	
	
SELECT * FROM COMMENTS;


DELETE NOTICES;

--SELECT NVL(MAX(TO_NUMBER(CODE)), 0) FROM NOTICE
SELECT ISNULL(MAX(CAST(CODE AS INT)), 1)+1 AS CODE FROM NOTICES

-- getList query
SELECT * FROM 
(
	SELECT 
		ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM,
		NOTICES_VIEW.*
	FROM NOTICES_VIEW
	WHERE TITLE LIKE '%%'
) N
WHERE NUM BETWEEN 1 AND 10

-- getCount query
SELECT COUNT(*) COUNT FROM 
(
	SELECT 
		ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM,
		NOTICES_VIEW.*
	FROM NOTICES_VIEW
	WHERE TITLE LIKE '%%'
) N








INSERT INTO NOTICES(
	CODE,
	TITLE,
	CONTENT,
	WRITER)
VALUES(
	'981',
	'jasper를 만나고...',
	'제스퍼.... 도와줘~~',
	'newlec'
	)


	
CREATE VIEW REVIEW_NOTICE_VIEW
AS
SELECT NUM, CODE, TITLE, CONTENT, REGDATE, HIT,MOVIE_TITLE ,CNT FROM
(
  SELECT ROWNUM NUM ,CODE, TITLE, CONTENT, REGDATE, HIT,MOVIE_TITLE, CNT FROM
  (
    SELECT N.CODE, N.TITLE, N.CONTENT, N.REGDATE, N.HIT,N.MOVIE_TITLE,COUNT(C.CODE) CNT
    FROM REVIEW_NOTICE N 
    lEFT OUTER JOIN MEMBER M
      ON N.WRITER = M.MID
    WHERE TITLE LIKE '%%'
    GROUP BY ROWNUM , N.CODE, N.TITLE, N.CONTENT, N.REGDATE,N.MOVIE_TITLE ,N.HIT
    ORDER BY N.REGDATE DESC
  )
)
	
CREATE VIEW REVIEW_NOTICE_VIEW
AS
-- 조회문장을 만들자(덧글 몇개 달렸는지 알기 위해서)
SELECT N.*, COUNT(C.CODE) AS CMTCNT 
   FROM REVIEW_NOTICE N LEFT OUTER JOIN 
   REPLE C ON N.CODE = C.NOTICE_CODE
   
GROUP BY N.Code,N.Writer, N.Title, N.Content,N.Regdate,N.Hit;
