SELECT * FROM REVIEW_NOTICE;


CREATE VIEW NOTICES_VIEW
CREATE VIEW NoticesView
AS
SELECT N.*, COUNT(C.CODE) AS CmtCnt 
FROM 
	NOTICES N LEFT OUTER JOIN COMMENTS C ON N.CODE = C.NOTICECODE
GROUP BY N.Code, N.Title, N.Writer, N.Content, N.RegDate, N.Hit; 
	
	
SELECT * FROM NOTICES_VIEW;


DELETE NOTICES;

--SELECT NVL(MAX(TO_NUMBER(CODE)), 0) FROM NOTICE
SELECT ISNULL(MAX(CAST(CODE AS INT)), 1)+1 AS CODE FROM NOTICES

-- getList query
SELECT * FROM 
(
	SELECT 
		ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM,
		NOTICES_VIEW.*
	FROM NOTICES_VIEW
	WHERE TITLE LIKE '%%'
) N
WHERE NUM BETWEEN 1 AND 10

-- getCount query
SELECT COUNT(*) COUNT FROM 
(
	SELECT 
		ROW_NUMBER() OVER (ORDER BY REGDATE DESC) NUM,
		NOTICES_VIEW.*
	FROM NOTICES_VIEW
	WHERE TITLE LIKE '%%'
) N








INSERT INTO NOTICES(
	CODE,
	TITLE,
	CONTENT,
	WRITER)
VALUES(
	'981',
	'jasper를 만나고...',
	'제스퍼.... 도와줘~~',
	'newlec'
	)


	
CREATE VIEW REVIEW_NOTICE_VIEW
AS
SELECT NUM, CODE, TITLE, CONTENT, REGDATE, HIT, CNT FROM
(
  SELECT ROWNUM NUM ,CODE, TITLE, CONTENT, REGDATE, HIT, CNT FROM
  (
    SELECT N.CODE, N.TITLE, N.CONTENT, N.REGDATE, N.HIT, COUNT(C.CODE) CNT
    FROM REVIEW_NOTICE N 
    lEFT OUTER JOIN MEMBER M
      ON N.WRITER = M.MID
    LEFT OUTER JOIN "COMMENT" C
      ON N.CODE = C.NOTICE_CODE
    WHERE TITLE LIKE '%제%'
    GROUP BY ROWNUM , N.CODE, N.TITLE, N.CONTENT, N.REGDATE, N.HIT
    ORDER BY N.REGDATE DESC
  )
)
	

